#include <stdio.h>
#include <stdlib.h>
#include "structs.h"


int toInt(char *string){
    // Get bbase of nput
    // Cut of 0x, 0b, 0o or whatever if necesarry
    // return strtol

    return 0; //strtol();
}

// Basic driver for testing
int main(){
    
   char str[30] = "10";
   long ret;

   ret = strtol(str, NULL, 8);
   printf("The number(unsigned long integer) is %ld\n", ret);

   return 0;
}

// Generate output file from program generated by parser
int generateCode(Program *program, FILE *outFile){
    for (int i = 0; i < program->length; i++){
        switch (program->Instructions[i].instructionType) {
            case GLOBAL:
                printf("Global entrypoint found: %s\n", program->Instructions[i].operands[0].value);
                break;
            
            default:
                break;
        }
    }
    return 0;
}

