#include <stdio.h>
#include <stdlib.h>
#include "structs.h"

// Convert string to int regarudless of base
int toInt(char *string){
    // Get bbase of nput
    int base = 10;
    
    if (string[1] == 'x') base = 16;
    if (string[1] == 'o') base = 8;
    if (string[1] == 'b') base = 2;

    // Cut of 0x, 0b, 0o or whatever if necesarry
    int strStart = 0;
    if (base != 10) strStart = 2;
    char *trimmedStr = malloc(0);

    while(string[strStart] != '\0'){
        if (base == 10) {
            // Base 10 is clean copy
            trimmedStr = realloc(trimmedStr, strStart+1); 
            trimmedStr[strStart] = string[strStart];
        } else {
            // Other bases need first two chars trimmed
            trimmedStr = realloc(trimmedStr, strStart-1);
            trimmedStr[strStart-2] = string[strStart];
        }
        strStart++;
    }

    // return strtol
    return strtol(trimmedStr,NULL,base);
}

// Generate output file from program generated by parser
int generateCode(Program *program, FILE *outFile){
    // Track address in memory of the current instruction
    int address = 0;

    for (int i = 0; i < program->length; i++){
        Instruction instruction = program->Instructions[i];
        switch (instruction.instructionType) {
            case GLOBAL:
                printf("Global entrypoint found: %s\n", instruction.operands[0].value);
                break;

            case ORG:
                address = toInt(++instruction.operands[0].value);
                printf("Org to: %i\n", address);
                break;
            
            case LABEL:
                printf("Found label '%s'\n", instruction.operands[0].value);

            default:
                printf("INVALID/UNIMPLEMENTED TOKEN TYPE %i IN GENERATION\n", instruction.instructionType);
                exit(1);
                break;
        }
    }
    return 0;
}

