; Comment
o0***, POL MIL, POH MIH, RD II CE, CR  ; NOP
o10***, POL MIL, POH MIH, RD II CE, RD AI CE, CR  ; LD R I
o11***, POL MIL, POH MIH, RD II CE, RD BI CE, RD MIH CE, BO MIL, RD AI, CR  ; LD R MA
o12***, POL MIL, POH MIH, RD II CE, RD BI CE, RD MIH CE, BO MIL, WR AO, CR  ; LD MA R
o20***, POL MIL, POH MIH, RD II CE, RD BI CE, RD PIH, BO PIL, CR  ; JP I
o30***, POL MIL, POH MIH, RD II CE, RD BI CE, EO AI, CR  ; ADD I