; Comment
o00***, POL MIL, POH MIH, RD II CE, CR  ; NOP
o01***, POL MIL, POH MIH, RD II CE, POL PIL RSTA, AO AI, AO MIL, AO MIH, RD BI, EO MIL, POH WR, EO BI, EO MIL, POL WR, AO MIL, EO WR, POL MIL, POH MIH, RD PIH CE, RD PIL, CR  ; CALL I
o10***, POL MIL, POH MIH, RD II CE, POL MIL, POH MIH, RD AI CE, CR  ; LDA I
o20***, POL MIL, POH MIH, RD II CE, POL MIL, POH MIH, RD BI CE, CR  ; LDB I